name: env_sidescantools_cli
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - geopy
  - numpy==2.3.3
  - pyproj
  - conda-forge::gdal=3.10.3
  - pyyaml
  - pygmt==0.17.0
  - rioxarray==0.18.1
  - rasterio==1.4.3
  - scipy
  - scikit-image
  - pip
  - pip:
      - pyxtf==1.4.2
      - utm==0.8.1
